name: slim-frontend

services:
  nginx:
    container_name: slim-frontend-nginx
    build:
      context: docker
      dockerfile: development/nginx/Dockerfile
    ports:
      - "${HTTP_PORT:-8088}:80"
    volumes:
      - ./:/app
    networks:
      - proxy

  php-fpm:
    container_name: slim-frontend-php-fpm
    build:
      context: docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./:/app
    networks:
      - proxy

  php-cli:
    container_name: slim-frontend-php-cli
    build:
      context: docker
      dockerfile: development/php-cli/Dockerfile
    volumes:
      - ./:/app
    networks:
      - proxy

networks:
  proxy:
    external: true
